### ISSUE TITLE
Incompatibility between FEBio2 and FEBio3: Elements in an ElementSet must belong to the same part.

### ISSUE THREAD

**Issue by gateshian** [febiosoftware/FEBio#1]
The attached file runs fine in FEBio2 but produces the following error in FEBio3:
 *************************************************************************
 *                                ERROR                                  *
 *                                                                       *
 * Elements in an ElementSet must belong to the same part.               *
 *                                                                       *
 *************************************************************************
The issue arises because an object consists of two parts with hex8 and penta6 elements, and boundary conditions are being applied on a face that includes quad4 and tri3 elements.  Backward compatibility needs to be enforced for this very basic type of situation.

[temp.feb.zip](https://github.com/febiosoftware/FEBio/files/4819787/temp.feb.zip)

**Comment by SteveMaas1978** [comment]
This should be fixed now.
