### ISSUE TITLE
Yeoh Model

### ISSUE THREAD

**Issue by SteveMaas1978** [febiosoftware/FEBio#11]
Would it be possible to implement the Yeoh model in FEBio?

**Comment by DebjitHore** [comment]
Hi, @SteveMaas1978 just wanted to ask if you're currently working to implement the Yeoh model in FEBio?

**Comment by SteveMaas1978** [comment]
Hi,

We do not have a Yeoh model in FEBio, but I can look into adding it. However, it might be a while before I can get to it. You could also consider implementing it yourself as a plugin. If you are interested in that approach, please take a look at the developer’s documentation (FEBio: FEBio Developer's Manual<https://help.febio.org/doxygen/html/index.html>) and let me know if you have any questions.

Best,

Steve

**Comment by gateshian** [comment]
I have implemented and committed a model for the Yeoh material.  Please try it out and report bugs if any.
