### ISSUE TITLE
Nan error while running a FSI contact problem

### ISSUE THREAD

**Issue by Sachin4728** [febiosoftware/FEBio#12]
Hi
I am getting an error while running an FSI contact problem. I have attached the related files here with this message. 
[FSI practice2 .zip](https://github.com/febiosoftware/FEBio/files/5275872/FSI.practice2.zip)

**Comment by gateshian** [comment]
Hi,
The FSI solver does not support sliding contact between a FSI boundary and a rigid body.  In essence your analysis examines contact between a rigid solid and the free surface of a fluid domain, which is not within the modeling capabilities of this analysis type.
