### ISSUE TITLE
Assigning element data to prestrain gradient doesn't work

### ISSUE THREAD

**Issue by SteveMaas1978** [febiosoftware/FEBio#14]
Users cannot map element data to the F0 parameter of the prestrain gradient. 

This is due to the changes in FEBio3 related to defining heterogenous parameters. The prestrain material has not been updated to make use of this new framework.

**Comment by spietz** [comment]
Has this been resolved in the newly released version 3.2?

**Comment by SteveMaas1978** [comment]
Yes, this should work in FEBio 3.2. I'm attaching an example file. Please give it a try and let me know if it works as expected for you. 

Steve
[prestrain_map.zip](https://github.com/febiosoftware/FEBio/files/5973416/prestrain_map.zip)

**Comment by spietz** [comment]
Yes, made it work by specifying the gradient tensor as 
```
<F0 type="map">F0_map</F0>
````
and creating an ElementData with this name as in your example file, thanks.
