### ISSUE TITLE
type=”math” attribute to the parameter’s definition

### ISSUE THREAD

**Issue by ashkanalmasi** [febiosoftware/FEBio#15]
Hello,

The type=”math” attribute works for E but it makes an error for phi0 (in biphasic). I am wondering to know what's the reason for that since they are both model parameter.

Please see the attached zip file.

Case_A.feb which is type=”math” for E. It works properly.
Case_B.feb which is type=”math” for phi0. I had an error.

> tag "phi0" (line 35) : invalid attribute "type"

Thanks!

[files.zip](https://github.com/febiosoftware/FEBio/files/5683492/files.zip)

**Comment by SteveMaas1978** [comment]
Since there are many materials in FEBio we have not updated all the parameters to make use of the new math and map options. However, the biphasic phi0 parameter was updated recently, so this should work now.
