### ISSUE TITLE
FEBio prints when -silent option is used

### ISSUE THREAD

**Issue by BabakNSafa** [febiosoftware/FEBio#17]
When run FEBio 3.1.0 with the -silent flag in Mac it prints:
### Default linear solver: pardiso 
and in Windows it prints
### Success loading plugin FEBioChem.dll (version 0.0.0)

Is there another way to suppress them?

**Comment by SteveMaas1978** [comment]
This issue is now fixed. The command line option -silent will now also suppress the configuration output (which is what you were seeing).
