### ISSUE TITLE
FEBio3 <laugon> compatibility in 2.5 format specification

### ISSUE THREAD

**Issue by SotirisKak** [febiosoftware/FEBio#18]
Febio 3.1.0 doesn't recognize "laugon" tag inside the "material" in FEBio files using 2.5 format. 
[Uniaxial_2_5.txt](https://github.com/febiosoftware/FEBio/files/5697878/Uniaxial_2_5.txt).

**Comment by SteveMaas1978** [comment]
The reason for this is that in FEBio3 this is no longer a material property. It is a property of the domains. If you wish to use this feature, I recommend converting the file to the 3.0 format and then setting the option in the corresponding MeshDomains sections. Let me know if that work-around works for you.
