### ISSUE TITLE
Segmentation fault when using more than 2 rigid connectors

### ISSUE THREAD

**Issue by spietz** [febiosoftware/FEBio#2]
Using more than 2 rigid connectors in a structural analysis gives a segmentation fault at the beginning of 2nd time step (I have tried both "rigid spring" and "rigid damper"). 
The error may be reproduced by running the small input file [oscillator.feb.txt](https://github.com/febiosoftware/FEBio/files/4958517/oscillator.feb.txt) , which solves in febio2.9 but in febio3 it fails unless I remove 1 or 2 springs (~line 82).

**Comment by SteveMaas1978** [comment]
This issue should be fixed now. Let us know if you still have problems.
