### ISSUE TITLE
material mapping

### ISSUE THREAD

**Issue by petr-henys** [febiosoftware/FEBio#24]
Hello,
I would like to use FEBio as the main solver for bone mechanics and damage, which requires mapping the scalar field of bone density obtained from CT onto FE space (discontinuous Galerkin). Is similar functionality available in FEBio solver?

**Comment by JeffWeissUT** [comment]
Yes you can do this with FEBio.  For questions like this that are not bug reports or feature requests, please use the FEBio forums here:  https://forums.febio.org/
