### ISSUE TITLE
VTK output option

### ISSUE THREAD

**Issue by ankushaggarwal** [febiosoftware/FEBio#31]
Is it possible to create an option to create output files in vtk format?

**Comment by steffenger** [comment]
Is there any update on the situation? We would really appreciate a direct vtk outout option, since we need this file format for post processing. 

best regards

steffen

**Comment by matthiaskoenig** [comment]
This would be an important feature, or alternatively a method to batch convert `*.xplt` results to `vtk`. We have many simulation runs and manually converting each of the results to VTK via FEBio Studio is very time consuming. 
I.e. either the possibility for storing VTK in addition to xplt simulation results or an option in FEBio Studio to convert a set of `*.xplt` to vtk in a single run would be great.

**Comment by utsekaj42** [comment]
I have implemented a python interface to convert XPLT to VTK, so this may be of use to those interested in this topic. See example.py [here](https://gitlab.com/utsekaj/febpy ). I won't guarantee it will work with all models, but it may not be too hard to improve it to cover additional model structures.

**Comment by SteveMaas1978** [comment]
As of FEBio 4.4, FEBio can now export directly to VTK file format. To try it, set the type attribute of the plotfile tag to "vtk":

```
<plotfile type="vtk">
  <var type="displacement"/>
  <var type="stress"/>
</plotfile>
```

Note that currently the VTK legacy format is used, which does not support all the features and output options of the febio plotfile. However, most commonly used nodal and element plot variables should be supported. 

I'm going to close this issue now. If you find any problems or like to see any enhancements to this feature, please open a new issue.
