### ISSUE TITLE
Mapping parameters not working for Ogden materials

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [febiosoftware/FEBio#33]
@SteveMaas1978 I have a model where this runs fine: 
```xml
        <material id="1" name="Material1" type="neo-Hookean">
            <E type="map">MaterialParameterMap1</E>
            <v>4.0000000e-01</v>
        </material>
```

But the following fails with an FEBio error saying `tag "c1" (line 46) : invalid attribute "type" `:

```xml
        <material id="1" name="Material1" type="Ogden unconstrained">
            <c1 type="map">MaterialParameterMap1</c1>
            <m1>2</m1>
            <cp>5.0050000e+01</cp>
        </material>
```
Is the material parameter mapping not implemented for all materials? I also tried the `Ogden` form but got the same issue.

**Comment by SteveMaas1978** [comment]
This feature is now implemented. Please give it a try and let us know if you run into any issues.
