### ISSUE TITLE
higher order pyramid elements

### ISSUE THREAD

**Issue by BabakNSafa** [febiosoftware/FEBio#35]
I was wondering if it would please consider adding support for higher order pyramid elements? These elements are quite handy in making unstructured tet-based meshes, but for the nearly-incompressible models the linear elements are no good.
![image](https://user-images.githubusercontent.com/35350283/142692320-ca27d24c-a928-409e-a570-752a3fe20baa.png)

**Comment by SteveMaas1978** [comment]
Hi Babak,

I think you already know that Gerard implemented 13-node pyramid elements, so just wondering if this issue can be closed? 

Thanks,

Steve

**Comment by BabakNSafa** [comment]
Hi Steve, yes I agree. Best, Babak
