### ISSUE TITLE
Prescribed displacement with specific vectors

### ISSUE THREAD

**Issue by pbmor** [febiosoftware/FEBio#39]
Hi,
I am looking to add a prescribed displacement on the edges of my cylindrical mesh. I would like to a specific displacement vector for each node at every time step and I am unsure how it should be done.

Any guidance would be greatly appreciated. Thanks,
Pete

**Comment by jpeloquin** [comment]
Although I'm not part of the FEBio development team, I've solved problems like this before and may be able to help.  First, could you clarify how the displacement vectors are supposed to vary (a) across nodes / space or (b) across time, in terms of both direction and magnitude?  And if they vary, do they do so according to a shared constraint, such as enforcing a particular deformation tensor across all constrained nodes?

**Comment by pbmor** [comment]
> Although I'm not part of the FEBio development team, I've solved problems like this before and may be able to help. First, could you clarify how the displacement vectors are supposed to vary (a) across nodes / space or (b) across time, in terms of both direction and magnitude? And if they vary, do they do so according to a shared constraint, such as enforcing a particular deformation tensor across all constrained nodes?

Hi jpeloquin, thanks for responding to my query. 

My displacements come from 4DE images from ultrasounds that have been registered to a mesh. Essentially I want the edges of my open ended cylindrical mesh to move due to the external forces (in this case the impact of the heartbeat/blood flow) although the average motion of the whole mesh has been removed. I have normalised displacements for each node and/or element for every time frame. As the displacements come from the image rather than a preassigned deformation there is no shared constraint. 

It would be possible to get an average of the displacements of the edges so that the displacements of each node could be the same, although ideally each node, of the edges of the mesh, would have it's own displacement at each time so as to compare the simulated version and the recorded version.

Thanks,
Pete

**Comment by jpeloquin** [comment]
@pbmor If I understand correctly, every node needs to have a unique data-driven (δx, δy, δz) vs. time displacement sequence.  I believe this is accommodated in FEBio XML 3.0 by defining a 1-node `<NodeSet>` (under `<Mesh>`) for each node, a corresponding `<NodeData>` element (under `<MeshData>`) for each node,  a `<load_controller>` element (under `<LoadData>`) for each displacement axis for each node, and a `<bc type="prescribe">` element (under `Step/Boundary`) for each displacement axis for each node.  Which is tiring just to describe, never mind write out the XML.  (This was easier a decade ago with FEBio XML 1.2—back then you only needed a `Boundary/prescribe/node` element and a `<loadcurve>` element for each node for each displacement axis.)

Anyway, I've written some Python scripts to deal with situations like this in my own work.  Here's a simple example that you should be able to modify to use your mesh & displacements: [uniaxial tension with simultaneous 180° rotation](https://github.com/jpeloquin/waffleiron/blob/master/examples/uniaxial_stretch_with_180%C2%B0_flip/create_180%C2%B0_flip_case.py).

If you elect to try this approach, please raise any problems related to my scripts in my repo, not the FEBio repo.  My scripts don't support every single FEBio feature so `load_model()` might throw an error depending on what features your full model uses.  In that case you could generate XML for the displacement boundary conditions using a simpler model and copy it into your full model file, or let me know what's missing and I'll add it if I can.
