### ISSUE TITLE
Add or link to contributing guidelines

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [febiosoftware/FEBio#4]
Add contributing guidelines e.g. in the form of a CONTRIBUTING.md file, and link to it in the readme. 

Here is an example for GIBBON: 
https://github.com/gibbonCode/GIBBON/blob/master/CONTRIBUTING.md

Here is another template: 
https://gist.github.com/PurpleBooth/b24679402957c63ec426

**Comment by SteveMaas1978** [comment]
CONTRIBUTING.md file was added to repo.
