### ISSUE TITLE
With prescribed node displacement, (non-rigid) node reaction forces are zero

### ISSUE THREAD

**Issue by jpeloquin** [febiosoftware/FEBio#40]
Given a prescribed displacement boundary condition applied to nodes and "reaction forces" specified as a plotfile variable,  FEBio ≥ 3.4 output zero for all 3 reaction force components for all nodes, whereas FEBio ≤ 3.3 output nonzero nodal reaction forces.  The FEBio 3.4 release was also when rigid body reaction forces were moved from node state data to object state data, but this issue is *not* about rigid body forces, just regular node reaction forces.  No rigid bodies are involved.

**To reproduce**, run the attached .feb file (which has been given the .txt extension so Github accepts it as an attachment) with various FEBio versions and check the reaction force output in FEBio Studio, or your tool of choice.  The file is a toy example of confined compression.

**Expected**: All boundary nodes subject to confinement (prescribed displacement = 0) should have nonzero reaction force associated with this constraint.

**Actual**: All nodes have zero reaction force.

| FEBio | Non-rigid node reaction forces |
|------- | --------------------------------|
| 3.2.0 | Nonzero                        |
| 3.3.3 | Nonzero                        |
| 3.4.0 | Zero                           |
| 3.5.1 | Zero                           |
| 3.6.0 | Zero                           |

The practical impact of this is that it is difficult to measure the confinement force in a confined compression simulation.  It is often worthwhile to check these reaction forces to see if the simulated confinement switches from compression to tension.

[node_reaction_force_check.feb.txt](https://github.com/febiosoftware/FEBio/files/8112763/node_reaction_force_check.feb.txt)

**Comment by SteveMaas1978** [comment]
Hi John,

At some point the algorithm that extracts the reaction forces was changed, and the element stress was used to calculate the reaction forces. (I think this was done to provide reaction forces for all nodes, not just prescribed ones.) However, it looks like this is only working for elastic problems, not biphasic ones. I'll take a closer look and see if I can get it working for all problems again. 

Best,

Steve

**Comment by gateshian** [comment]
Hi,
As far as I can tell this has been fixed, since the attached test problem now produces non-zero reaction forces.  So I am closing this issue.
Best,
Gerard
