### ISSUE TITLE
Bug restarting using mapped materials

### ISSUE THREAD

**Issue by spietz** [febiosoftware/FEBio#41]
FEBio v3.6 restarting simulation with mapped material parameter does not work.

Here is a simple [example](https://github.com/febiosoftware/FEBio/files/8114250/mapped_material.feb.txt)
```
febio3 -i mapped_material.feb -dump -break 0.1
```
then quit and restart:
```
febio3 -r mapped_material.dmp
```
If the material parameter is not mapped, restarting the example works fine.

**Comment by SteveMaas1978** [comment]
Hi Henrik,

It looks like restart is working correctly now. Can you please try it again with the latest develop version? 
I do recommend defining a plotfile section in the input file, otherwise the plotfile is not reconstructed correctly when restarting. 
Let me know what you find.

Thanks,

Steve

**Comment by spietz** [comment]
Hi Steve,

Restarting the test problem works with the current develop version.
 
Thanks a lot,
Henrik
