### ISSUE TITLE
Save Contact Surfaces

### ISSUE THREAD

**Issue by lancef37** [febiosoftware/FEBio#44]
When adding or deleting parts to a model (or any mechanism that adds or deletes elements), contact surfaces are lost as the mesh gets renumbered. 

It would be a great feature to have the ability to retain contact surfaces, as long as the contact surfaces themselves aren't changing.

This could take the form of having the ability to "disable" parts during export, so the parts don't actually have to be deleted.

**Comment by lancef37** [comment]
I've found a workaround for this. If the <Elements ...> section for a specific part is deleted in the .feb file, the model can then be reloaded into Studio without the part, yet all contact is remained, since the nodes were not deleted and function as placeholders for the surfaces. When the model is run, the isolated nodes are deleted, and still the contact surfaces are maintained.

All that to say.. if a part needs to be deleted without losing contact surface definitions, delete the <Elements ..> section for that specific part in the .feb file directly.

Lance

**Comment by gateshian** [comment]
Hi Lance,
That's great, thanks for resolving this issue and sharing this workaround.
Best,
Gerard
