### ISSUE TITLE
Add a roadmap

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [febiosoftware/FEBio#5]
@SteveMaas1978 

could you add a basic ROADMAP.md (example here: https://github.com/gibbonCode/GIBBON/blob/master/ROADMAP.md)

In it you could highlight some short and long term goals and milestones for FEBio. It would be nice to also include a view to adding the discussed topology optimization functionality to FEBio in the roadmap. 

Using the roadmap users wanting to contribute gain an understanding in terms of what the grand plan is and where they might be able to help. 

You can link to the roadmap in your readme and also the contributing guidelines.

**Comment by Kevin-Mattheus-Moerman** [comment]
@SteveMaas1978 :wave:

**Comment by SteveMaas1978** [comment]
@Kevin-Mattheus-Moerman I created a draft and send it to the team. Once I get the green light, I'll upload it to git.

**Comment by SteveMaas1978** [comment]
Initial draft of road map added.
