### ISSUE TITLE
Representing growth using the prestrain gradient?

### ISSUE THREAD

**Issue by asrvsn** [febiosoftware/FEBio#55]
Hi,

From the [docs](https://help.febio.org/docs/FEBioUser-3-6/UM36-Section-4.17.html) it appears to me that the prestrain gradient (for incompressible materials) should have determinant 1. Is this correct? 

When this is not the case, I frequently encounter `negative Jacobian`. I'm trying to represent a time-dependent growth process in an incompressible material. Is this possible to do via the prestrain gradient with determinant < 1?

**Comment by gowtham2598** [comment]
Hi, may i know how you resolved this issue? because I encounter the negative Jacobian issue during prestrain.
