### ISSUE TITLE
-nan or -1.#IND for principal component logfile output

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [febiosoftware/FEBio#6]
@SteveMaas1978 

In one of [my GIBBON demos](https://www.gibboncode.org/html/DEMO_febio_0056_cylinder_embedded_probe_02.html) I output principal Cauchy stresses, for a selection of solid elements (tet4), to a log file, i.e. `s1;s2;s3`. 

Usually the output is in the following form: 
`430,4.84829e-05,4.72102e-05,4.31673e-05`
Where the first number, `430` is the element id and the other 3 numbers would be `s1`, `s2`, and `s3`. 

For some elements however I get the following output for Linux:
`430,-nan,-nan,-nan`
and the following for Windows: 
`430,-1.#IND,-1.#IND,-1.#IND`

I suspect this is this because no reliable eigenvalues are found for that tensor or the outcome is complex? Perhaps you should detect the zero/complex case and replace it by all zeros? Would it make more sense to have `0` instead of `-nan` or `-1.#IND`? If you do want to export something other than 0, perhaps you can make it consistent across systems e.g. use `nan` throughout (handling `NaN` is easier/standard and `-1.#IND` throws an error or requires special treatment) 

Thanks. I attach the .feb file (had to rename it to txt for GitHub) here if you want to run it yourself. 

[tempModel.txt](https://github.com/febiosoftware/FEBio/files/5057392/tempModel.txt)

**Comment by SteveMaas1978** [comment]
The problem was caused by a division by zero when the matrix is zero. A check was added for this and if the matrix is all zeroes, it now returns all zeroes for the eigenvalues.

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks @SteveMaas1978. Can you ping me when this is available in a binary for download over at: https://febio.org/febio/febio-downloads/? 

Would be great if you offered download links on the website for the "stable version", and also any latest "nightly builds".

**Comment by Kevin-Mattheus-Moerman** [comment]
@SteveMaas1978 is this implemented now?

**Comment by SteveMaas1978** [comment]
It is. Give it a try and let us know if you still find issues.
