### ISSUE TITLE
Logfile output initial states are zero for stretches

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [febiosoftware/FEBio#62]
@SteveMaas1978 The initial state for stretch type data should be 1. However the log files exported by FEBio currently export a 0. 

For instance, using: 

```xml
        <logfile file="tempModel.txt">          
            <element_data data="U1;U2;U3" delim="," file="tempModel_stretch_prin_out.txt"/>
        </logfile>
```
Leads to a log file containing: 
```
*Step  = 0
*Time  = 0
*Data  = U1;U2;U3
1,0,0,0
2,0,0,0
3,0,0,0
...
```
I would check this for other stretch type data exports too if possible.

**Comment by gateshian** [comment]
Hi Kevin,
Thanks for catching that.  This bug has now been fixed.
Best,
Gerard
