### ISSUE TITLE
Implementing 6-noded octahedral elements

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [febiosoftware/FEBio#63]
It would be great to have 6-noded (and maybe higher order ones too) octahedral elements. Would this be easy to add to FEBio?

**Comment by gateshian** [comment]
Hi Kevin,
Would you please provide a literature or online reference for this type of element, including shape functions?
Thanks, 
Gerard

**Comment by gateshian** [comment]
Hi Kevin,

You can use two pyramid elements to form an octahedron.  5-node (linear) and 13-node (quadratic) pyramid elements already exist in FEBio.  Meshes that contain such elements are generally imported from a meshing software that produces this type of elements.  FEBioStudio will also generate pyramid elements when revolving a triangular surface about an axis that passes through one edge of that surface.

Best,

Gerard
