### ISSUE TITLE
problem with logging contact pressure in "Sliding-node-on-facet" algorithm

### ISSUE THREAD

**Issue by BabakNSafa** [febiosoftware/FEBio#71]
I am trying to save contact pressure from the Sliding-node-on-facet algorithm into the log file, and it always gives zero for all faces. The problem exists at least with Febio 4.0 and 4.3.
Additional info:

- Sliding-elastic algorithm saves correct values
- Plotfile saves correct info
- Contact traction saved in log file is different from log file results in Sliding-node-on-facet.

Example files are attached.

[jobs.zip](https://github.com/febiosoftware/FEBio/files/12623960/jobs.zip)

**Comment by SteveMaas1978** [comment]
Hi Babak,

I think these issues have all been resolved, so closing now. Let us know if you do find any other issues.

Best,

Steve

**Comment by BabakNSafa** [comment]
Thanks, Steve.
