### ISSUE TITLE
Rigid body material needs description of rotation vector, conventions

### ISSUE THREAD

**Issue by SteveMaas1978** [febiosoftware/FEBio#8]
I can't find any documentation in the User's Manual or the Theory Manual that describes the representation of rigid bodies in FEBio. Users need to know how rotations are represented, etc.

**Comment by heikostark** [comment]
I have a similar problem. I wanted to describe the degrees of freedom for rigid-bodys and used <rigid_body ...> from the documentation 3.11.4. After examples, this tag has to be described in the Constraints section (3.14.). I use FEBio 2.9.1

**Comment by gateshian** [comment]
Section 6.3 "Rigid Body Dynamics" in the Theory Manual describes how rigid body rotation is modeled in FEBio. Admittedly it does not get into the details of the implementation (where quaternions are used to represent the rotation), but it does cover the theoretical background. More information about rigid body rotation is available in Section 7.9 Rigid Connectors, which describes how rigid bodies may be constrained together.

**Comment by gateshian** [comment]
I updated the User Manual 3.0 to describe rigid body motion and the meaning of the rotation components.
