### ISSUE TITLE
How can I run the test

### ISSUE THREAD

**Issue by jml-1** [febiosoftware/FEBio#93]
I can not find any like main.cpp to start the program

**Comment by jml-1** [comment]
![image](https://github.com/user-attachments/assets/55b6464b-40d6-4702-9516-661ef182b768)

**Comment by michaelrossherron** [comment]
If you have installed FEBio using the installers available on our website, then you should be able to run it from your terminal using the command febio4 on Linux or macOS, or by running febio4.exe on windows. 

If that doesn't work, or if you have any other questions or problems, please let us know about it in detail and we will do our best to help. 

Thanks,

Michael Herron

**Comment by michaelrossherron** [comment]
If you have further questions about how to start using our software, I suggest that you take a look at the tutorials in our Knowledgebase under the Getting Started heading, starting with [this tutorial](https://febio.org/knowledgebase/getting-started/account-registration-and-software-download/). 

If you still have questions about the software, then I would recommend asking them on our [forums](https://forums.febio.org/), as this page is usually used for reporting bugs. As such, I will be closing this thread. Please feel free to open a thread on our forums if you have more questions. 

Michael Herron
